# redis
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
#    lettuce:
#      pool:
#        max-active: 200
#        max-wait: 1500
#        max-idle: 10
#        min-idle: 1
