spring:
  data:
    # Elasticsearch 配置项
    elasticsearch:
      client:
        # 对应 ReactiveRestClientProperties 配置类
        reactive:
          endpoints: ${ELASTIC_ADDRESS:127.0.0.1}:${ELASTIC_PORT:9200} # ES Restful API 地址
