spring:
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/webflux-r2dbc  # r2dbc:mysql://127.0.0.1:3306/demo
    username: root
    password: 123456
    pool:
      initial-size: 5
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1

server:
  port: 8081
